networks:
  privateindexer-net:
    name: privateindexer-net
    driver: bridge
services:
  client:
    image: ghcr.io/humehouse/privateindexer-client:latest
    container_name: privateindexer-client
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
      DOWNLOADS_DIR: /path/to/downloads
      MAX_THREADS: 8
      FASTRESUME_INTERVAL: 60
      SCAN_INTERVAL: 15
      API_KEY: keyhere
      TORRENTING_PORT: 6881
      RADARR_URL: https://radarr.example.com
      RADARR_API_KEY: keyhere
      SONARR_URL: https://sonarr.example.com
      SONARR_API_KEY: keyhere
    volumes:
      - /path/to/client/data:/app/data
      - /path/to/movies:/path/to/movies
      - /path/to/tv:/path/to/tv
    networks:
      - privateindexer-net
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:80"
    logging:
      options:
        max-size: 10m
        max-file: 5
    build:
      context: .
      network: host
