networks:
  privateindexer-net:
    name: privateindexer-net
    driver: bridge
services:
  client:
    image: ghcr.io/humehouse/privateindexer-client:latest
    container_name: privateindexer-client
    restart: unless-stopped
    environment:
      MOVIE_DIR: /path/to/movies
      MOVIE_EXTENSIONS: mp4,mkv,m4v,avi
      SCANNER_THREADS: 8
      SCAN_INTERVAL: 15
      API_KEY: keyhere
      TORRENTING_PORT: 6881
    volumes:
      - /path/to/client/data:/app/data
      - /path/to/movies:/path/to/movies
    networks:
      - privateindexer-net
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:80"
    logging:
      options:
        max-size: 10m
        max-file: 5
    build:
      context: .
      network: host
